credentials:
  usernames:
    sortmanns:
      email: s.ortmanns@gmx.de
      name: Sebastian Ortmanns
      password: $2b$12$kif/6HDr681WslUHfgwcoO/82k404OMUxQeoXBYOPyqFFvj0MbRO2
    dzenner:
      email: dominik.zenner@augen-arzt-berlin.de
      name: Dominik Zenner
      password: $2b$12$yCCxWvl4CVw9HxHmpj2DGu5dX0RC/EUju7WZ6TKbE0w3kChsILCg6
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
      - sebastian.ortmanns@inovex.de
